name: scraping_insider_trading
channels:
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pandas=1.3.2
  - jupyter=1.0.0
  - matplotlib=3.4.2
  - seaborn=0.11.2
  - pip:
    - requests==2.26
    - beautifulsoup4==4.10.0
    - lxml==4.6.4
    - tqdm==4.62.3